return {
  -- You can also add new plugins here as well:
  -- Add plugins, the lazy syntax
  -- "andweeb/presence.nvim",
  -- {
  --   "ray-x/lsp_signature.nvim",
  --   event = "BufRead",
  --   config = function()
  --     require("lsp_signature").setup()
  --   end,
  -- },
  -- { 
  --   "briones-gabriel/darcula-solid.nvim", 
  --   dependencies = {"rktjmp/lush.nvim",},
  -- },
  -- {
  --   'navarasu/onedark.nvim',
  --   config = function()
  --     require('onedark').setup {
  --       style = 'dark'
  --     }
  --   end
  -- },
}
